// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6HAv79b-5byeLFV7PfW_4sJqfEqApbLc',
    appId: '1:223326884779:web:221305d7225efcb3cd38ee',
    messagingSenderId: '223326884779',
    projectId: 'flutter-snap-todo',
    authDomain: 'flutter-snap-todo.firebaseapp.com',
    storageBucket: 'flutter-snap-todo.appspot.com',
    measurementId: 'G-MREZN3S9VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhdTM7D5EbZRmXq5qNL235nuTvwrF3rlc',
    appId: '1:223326884779:android:5cffd3c11d66e88ecd38ee',
    messagingSenderId: '223326884779',
    projectId: 'flutter-snap-todo',
    storageBucket: 'flutter-snap-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB9GEY52OQuv2yMMn__OvJzoMK54zpsbI',
    appId: '1:223326884779:ios:285adcc0abf27307cd38ee',
    messagingSenderId: '223326884779',
    projectId: 'flutter-snap-todo',
    storageBucket: 'flutter-snap-todo.appspot.com',
    iosClientId: '223326884779-90i5ls5265006ov4f4g5uj8ejhfif5dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.snapTodo',
  );
}
